name: Auto apply triage label and default project

on:
  issues:
    types:
      - opened
      - reopened

jobs:
  label_and_assign_project:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      # For an org-level project, you often need:
      # organization-projects: write
      # or
      # repository-projects: write
    steps:
      # Step 1: Add "triage" label if no milestone
      - name: Add "triage" label if no milestone
        if: ${{ github.event.issue.milestone == null }}
        run: gh issue edit "${{ github.repository }}#${{ github.event.issue.number }}" \
          --add-label "triage"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 2: Assign the issue to the org-level project #8
      - name: Add issue to org-level project #8
        run: gh project item-add 8 \
          --content-id "${{ github.event.issue.node_id }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
